version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/my-app/learningpipeline/
permissions:
  - object: /home/ubuntu/my-app/learningpipeline/scripts/
    owner: ubuntu
    group: ubuntu
    mode: 777
  - object: /opt/codedeploy-agent/deployment-root/
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu

# test
